name: Deploy Strapi to Railway

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar código
      - uses: actions/checkout@v4

      # Passo 2: Instalar Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Passo 3: Cache de dependências
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      # Passo 4: Instalar e buildar
      - name: Install & Build
        run: |
          npm install
          npm run build

      # Passo 5: Deploy no Railway
      - name: Deploy to Railway
        uses: railwayapp/action@v1
        with:
          service-id: ${{ secrets.RAILWAY_SERVICE_ID }}
          token: ${{ secrets.RAILWAY_TOKEN }}
          environment: production